# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hao Ran
email: rangaogm@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi! This is Hao Ran, a PhD candidate at the Mullard Space Science Laboratory, Univerisity College London.
  My interests include studying the Sun at multiwavelengths, investigating the interaction between the particles in the heliosphere, and the effects of solar activities on the Earth's space environment.

#<<<<<<< HEAD
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ranhao1999.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#=======
twitter_username: jekyllrb
github_username:  RanHao1999

header:
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: Blog  # <-- blog.md
    - name: Research  # <-- work.md
      url: /research
    - name: CV    # <-- cv.md
      url: /cv
    - name: Notes # <-- notes.md
      url: /notes
footer:
  show_powered_by: true
  contact:
    - type: email
      name: ranhaogm@gmail.com
      value: ranhaogm@gmail.com
    - type: wechat
      value: Rise_Higher
      link: "#"
  follow:
    - type: twitter
      name: Twitter
      link: http://twitter.com/RAnHAoo
      username: "RAnHaoo"
    - type: instagram
      name: Instagram
      link: http://instagram.com/ranhao29
      username: "ranhao29"
    - type: github
      name: Github
      link: http://github.com/RanHao1999
      username: "RanHao1999"
    - type: researchgate
      name: ResearchGate
      link: https://www.researchgate.net/profile/Hao-Ran-11
      username: "Hao Ran"
    - type: orcid
      name: Orcid
      link: https://orcid.org/my-orcid?orcid=0000-0002-8234-6480
      username: "Hao Ran"
# Build settings
#<<<<<<< HEAD
#theme: bay_jekyll_theme
remote_theme: eliottvincent/bay
#=======
#>>>>>>> 5e0889ab68c2df599e5c79278c13f6383dc9a4cf
plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
